### ISSUE TITLE
Make it simpler to extend GdmAuthPrompt.AuthPrompt

### ISSUE THREAD

**Issue by nacho** [aws/dcv-gnome-shell-extension#1]
Today we need to carry a copy of GdmAuthPrompt.AuthPrompt to be able to extend it with a minor change. We need to work with upstream to be able to make it simpler to extend and like this have it easier on our side to maintain the extension.

**Comment by AlessandroBono** [comment]
The [upstream MR has been approved](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2399), we can close this.
